apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: uat
  labels:
    type: local
spec:
  # without whit the pv works
  #storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: dev
spec:
  #without whit the pv works
  #storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi