apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: uat
  labels:
    app: client-1-0
spec:
  type: NodePort
  selector:
    app: client-1-0
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-dp
  namespace: dev
  annotations:
    kubernetes.io/change-cause: "image name as a parameter"
    #deployment.kubernetes.io/revision: "2"
spec:
  replicas: 1
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: client-1-0
  template:
    metadata:
      labels:
        app: client-1-0
    spec:
      containers:
      - name: ${CLIENT_NAME}${CLIENT_VERSION} #client-1-2-ctr
        image: glatrofa/dev-ops-demo:client-1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80