apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: uat
  labels:
    app: mysql-8-0
spec:
  type: NodePort
  selector:
    app: mysql-8-0
  ports:
  - port: 3306
    nodePort: 30004
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dp
  namespace: uat
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql-8-0
  template:
    metadata:
      labels:
        app: mysql-8-0
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-8-0-ctr        
        env:
        - name: MYSQL_ROOT_PASSWORD
          #value: password
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ROOT_PASSWORD      
        ports:
        - containerPort: 3306
        volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-persistent-storage                    
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim