apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: dev
  labels:
    app: jenkins-2-204-5
spec:
  type: NodePort
  selector:
    app: jenkins-2-204-5
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dp
  namespace: dev
spec:
  replicas: 1
  strategy:
  type: Recreate
  selector:
    matchLabels:
      app: jenkins-2-204-5
  template:
    metadata:
      labels:
        app: jenkins-2-204-5
    spec:
      containers:
      - name: jenkins-2-204-5-ctr
        image: docker.io/jenkins/jenkins:2.204.5
        ports:
        - containerPort: 8080