apiVersion: v1
kind: Service
metadata:
  name: server-svc  
  namespace: prod
  labels:
    app: server-${VERSION}
spec:
  type: NodePort
  selector:
    app: server-${VERSION}
  ports:
  - port: 80
    nodePort: 30303
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dp
  namespace: prod
  annotations:
    kubernetes.io/change-cause: "image name as a parameter"
    #deployment.kubernetes.io/revision: "2"
spec:
  replicas: 2
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 100%
  selector:
    matchLabels:
      app: server-${VERSION}
  template:
    metadata:
      labels:
        app: server-${VERSION}
    spec:
      containers:
      - name: server-ctr-${VERSION}
        image: glatrofa/dev-ops-demo:server-${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 80