apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: dev
  labels:
    app: client-1-0
spec:
  type: NodePort
  selector:
    app: client-1-0
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-dp
  namespace: dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: client-1-0
  template:
    metadata:
      labels:
        app: client-1-0
    spec:
      containers:
      - name: client-1-0-ctr
        image: glatrofa/dev-ops-demo:client-1.1
        ports:
        - containerPort: 80