apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: dev
  labels:
    app: client-1-0
spec:
  type: NodePort
  selector:
    app: client-1-0
  ports:
  - port: 80
    nodePort: 30102
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-dp
  namespace: dev
  annotations:
    kubernetes.io/change-cause: "image name as a parameter"
    #deployment.kubernetes.io/revision: "2"
spec:
  replicas: 1
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: client-1-0
  template:
    metadata:
      labels:
        app: client-1-0
    spec:
      containers:
      - name: client-ctr-${VERSION}
        image: glatrofa/dev-ops-demo:client-${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 80