apiVersion: v1
kind: Service
metadata:
  name: server-svc  
  namespace: dev
  labels:
    app: server-1-0
spec:
  type: NodePort
  selector:
    app: server-1-0
  ports:
  - port: 80
    nodePort: 30003
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dp
  namespace: dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: server-1-0
  template:
    metadata:
      labels:
        app: server-1-0
    spec:
      containers:
      - name: server-1-0-ctr
        image: glatrofa/dev-ops-demo:server-1.0
        ports:
        - containerPort: 80