apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    app: jenkins-2-204-5
spec:
  type: NodePort
  selector:
    app: jenkins-2-204-5
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins-2-204-5
  template:
    metadata:
      labels:
        app: jenkins-2-204-5
    spec:
      containers:
      - name: jenkins-2-204-5-ctr
        #image: jenkins/jenkins:2.204.5
        #image: jenkins/jenkins:2.226-jdk11
        image: fsilletti/jenkins-docker:0.0.1
        securityContext:
            runAsUser: 0
        ports:
        - containerPort: 8080
        volumeMounts:
            - mountPath: "/var/jenkins_home"
              name: jenkins-persistent-storage                    
      volumes:
      - name: jenkins-persistent-storage
        emptyDir: {}
        #persistentVolumeClaim:
          #claimName: jenkins-pv-claim